### ISSUE TITLE
conditional for image type

### ISSUE THREAD

**Issue by yantei** [fleiflei/acf-admin-columns#10]
Hey,

My suggestion for line 357:

`$items_more = ($field_properties['type'] == 'gallery') ? count($field_value) - 1 : '';`

**Comment by fleiflei** [comment]
Hello @yantei ,

thank you for your suggestion. Since the time you wrote it, the plugin has been improved a lot. Do you still see a use case for your suggestion with the latest version? In that case please kindly post your pull request and I will gladly look into it. 

I will close this issue for now as I assume it might not apply to the latest version anymore...

Thank you and best regards,
Florian
